Import Libraries

In [1]:
import numpy as np
import pandas as pd

Import Data

In [3]:
data=pd.read_csv('/content/emails.csv')
data.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
data.describe()

              spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [5]:
list(data)

['text', 'spam']

In [6]:
data.isnull().sum()

text    0
spam    0
dtype: int64

Data Processing

In [7]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [8]:
v=set(stopwords.words('english'))
print(v)

{'to', 'why', 'do', 'off', "hasn't", 'out', 'you', 'his', 'what', 'nor', 'which', 'now', 'she', 'he', 'from', 'have', 'y', 'for', 'couldn', 'isn', 'o', 'once', 'down', 'most', "won't", 'd', 're', 'very', 'its', 'on', "you're", "aren't", 'no', 'against', 'these', 'does', "needn't", 'herself', 'during', "that'll", 'we', 'will', 'at', "he's", 'am', 'after', 'a', 'they', 'wasn', 'ours', 'about', 'because', 'yourself', 'mustn', 'and', "i've", "hadn't", "he'd", 'being', 'in', 'too', 'them', 'doesn', "wouldn't", "didn't", 'than', 'below', 'such', 'more', "weren't", "i'll", 'doing', 'were', 'whom', 'i', "i'm", 'our', 'is', 'some', 'are', 'before', "shouldn't", 'hasn', "shan't", 'only', 'aren', 'under', 'was', 'itself', 'it', "haven't", 'himself', 't', 'me', 've', "should've", 'shouldn', 'then', "they'll", 'between', 'wouldn', 'who', 'ma', 'not', 'here', "they're", 'of', 'until', 'ain', "she'll", "we'll", 'so', 'your', 'while', 'both', 'been', 'there', 'yourselves', 'how', "mightn't", "they've", "we'd", 'an', 'mightn', 'shan', 'few', 'each', 'where', 'by', 'all', 'again', 'haven', 'don', 'if', "we're", 'him', 'should', 'into', "she's", "they'd", 'other', 's', 'weren', 'won', 'didn', 'needn', 'themselves', 'theirs', 'm', 'over', "mustn't", "couldn't", "doesn't", 'be', "she'd", 'their', 'those', "we've", "wasn't", 'my', 'hadn', 'that', "it'd", 'can', 'having', 'when', "it's", 'yours', 'up', 'or', "you'd", "it'll", 'this', "he'll", 'll', "you've", 'the', 'myself', 'just', 'her', "isn't", "don't", 'ourselves', 'same', 'further', 'had', 'any', 'has', 'with', 'through', 'but', 'hers', 'own', 'above', 'did', "i'd", 'as', "you'll"}

In [9]:
import re

In [10]:
bag=[]
for i in range(0,5728):
  review=re.sub('[^a-zA-Z]',' ',data['text'][i])
  review=review.lower()
  review=review.split()
  lm=PorterStemmer()
  review=[lm.stem(word) for word in review if not word in set(v)]
  review=' '.join(review)
  bag.append(review)

In [11]:
bag

['subject natur irresist corpor ident lt realli hard recollect compani market full suqgest inform isoverwhelminq good catchi logo stylish statloneri outstand websit make task much easier promis havinq order iogo compani automaticaili becom world ieader isguit ciear without good product effect busi organ practic aim hotat nowaday market promis market effort becom much effect list clear benefit creativ hand made origin logo special done reflect distinct compani imag conveni logo stationeri provid format easi use content manag system letsyou chang websit content even structur prompt see logo draft within three busi day afford market break make gap budget satisfact guarante provid unlimit amount chang extra fee surethat love result collabor look portfolio interest',
 'subject stock trade gunsling fanni merril muzo colza attaind penultim like esmark perspicu rambl segovia group tri slung kansa tanzania ye chameleon continu clothesman libretto chesapeak tight waterway herald hawthorn like chisel morristown superior deoxyribonucl clockwork tri hall incred mcdougal ye hepburn einsteinian earmark sapl boar duan plain palfrey inflex like huzzah pepperoni bedtim nameabl attir tri edt chronographi optima ye pirogu diffus albeit',
 'subject unbeliev new home made easi im want show homeown pre approv home loan fix rate offer extend uncondit credit way factor take advantag limit time opportun ask visit websit complet minut post approv form look foward hear dorca pittman',
 'subject color print special request addit inform click click printabl version order form pdf format phone fax e mail ramsey goldengraphix com request addit inform click click printabl version order form pdf format golden graphix print azusa canyon rd irwindal ca e mail messag advertis solicit',
 'subject money get softwar cd softwar compat great grow old along best yet tradgedi finish death comedi end marriag',
 'subject great nnew hello welcom medzonlin sh groundsel op pleas introduc one iead onlin phar felicit maceuticai shop helter v shakedown r cosmopolitan l l blister l l bestow ag ac tosher l coadjutor va confid um andmanyoth sav inexpi e total confid leisur ntiaiiti worldwid polit hlpplng ov allus er miilion custom countri devit nice day',
 'subject hot play motion homeland secur invest terror attack unit state septemb ol chang secur landscap forese futur physic ogica secur becom paramount industri segment especia bank nationa resourc govern sector accord giga own subsidiari forrest research woridwid demand inform secur product servic set eclips b homeiand secur invest newsiett dedic provid reader inform pertain invest opportun lucr sector know event relat homeland secur happen lightn speed investor posit way take advantag current trend readi capit event yet happen homeland secur invest heip reader mind great excit present vinobl inc stock expect big thing near ong term symbol vnbl ob current price short term target price month target price believ vnbl ob give big return invest time much vnbl focu rfid radio frequenc identif technoiogi technolog use tini sensor transmit inform person object wireiessli vnbl aireadi industri pioneer rfid person locat technoiogi vnbl develop form rfid technolog allow compani govern wirelessli track asset resourc technoiogi huge potentia protect transport materiai design high risk fa wrong hand vnbl work integr two afor mention system order creat high secur space ocai deem necessari locat may take advantag system airport sea port mine nuciear faciiiti stock news drive short term price fresh news made vnbl hot buy news vnbl malibu calif busi wire june oo vinobl inc otcbb vnbl news hold compani seek identifi ong term growth opportun area homeland secur secur inform system secur servic announc today pian offer product servic wiil assist autom identif control equip asset tooi relat process use oi ga petrochem industri although smail wireiessli network rfid sensor monitor machin equip detect possibl problem becom seriou aiso deiiver safeti featur within oi weli oi mayb trap differ ayer rock aiong ga water detect specif iquid assist equip oper within specif precis opportun moment ensur certain advers condit occur well fili water rf base technoiogi applic rfid also provid safe transit materiai author handler limit entri personn specif ocat ensur personnel safeti essenti emerg faciiiti rfid tag wouid enabi custom track evaiuat empioye safeti danger applic technolog requir product hardwar oper harsh potentia hazard condit give valuabl safeti resourc asset vita custom rfid aiso assist custom suppli chain track oi ga chemica product extract refin saie retai evel vinobl viewpoint previousiy state applic vaiuabl mine industri protect measur countri natura resourc commod threat preserv fuei resourc import safeti u industri economi compani believ offer servic technoiogi appiic oil ga petrochem industri wil posit vinobl rapidli expand industri whiie take advantag access increas capit gioba spend compani wi requir growth compani goal aiso provid much need servic cost manag even sma est busi afford without safeti personnel asset current state constant threat outstand news growth potenti compani except alreadi hot industri vnbl ob stand truiy innov pioneer see big thing happen stock inform within emai contain forward look statement within mean section secur act section b secur exchang act statement express involv discuss respect predict expect belief pian project object goal assumpt futur event perform statement historica fact may forward ook statement forward ook statement base expect estim project time statement made invoiv number risk uncertainti couid caus actua result event differ materia present anticip forward look statement action may identifi use word project forese expect wi anticip estim beiiev understand statement indic certain action may couid might occur mani micro cap stock today compani addit risk factor worth note factor inciud limit oper histori compani advanc cash reiat parti sharehold unsecur basi one vendor relat parti major stockhoid suppli nineti seven percent compani raw materiai reiianc two custom fifti percent busi numer relat parti transact need rais capit factor other fuili speil compani sec fii urg read file invest rocket stock report repres inform contain messag state ail materia fact omit materi fact necessari make statement therein mislead ail inform provid within emai pertain invest stock secur must understood inform provid invest advic rocket stock report advis reader subscrib seek advic regist professiona secur repres decid trade stock featur within email none materi within report shal constru kind invest advic solicit mani compani verg bankruptci lose ail money invest stock publish rocket stock report regist invest advisor subscrib view inform herein ega tax account invest advic refer past perform compani speciaili seiect referenc base favorabi perform compani wouid need perfect time achiev resuit exampi given assur happen rememb aiway past perform never indic futur result thorough due diiigenc effort includ review compani file shouid complet prior invest compiianc secur act section b rocket stock report discios receipt tweiv thousand doilar third parti gem inc offic director affili sharehoid circuiat report gem inc posit stock wil se time without notic awar inher confiict interest resuit compens due fact paid advertis conflict al factua inform report gather pubiic sourc inciud limit compani websit sec fii compani press releas rocket stock report beiiev inform reliabi make guarante accuraci compiet use materia within email constitut accept term',
 'subject save money buy get thing tri ciall yet cannot even imagin like real man bed thing great errrectlon provid exactiy want ciali lot advantag viagra effect iast hour readi start within minut mix aicohol ship countri get right',
 'subject undeliver home base busi grownup messag subject home base busi grownup sent sun jan reach follow recipi tfi kpn com mon feb recipi name recogn mt id origin messag c us p ptt telecom l mtpi fjt q msexch im kpn telecom mtpi co unknown recipi',
 'subject save money buy get thing tri ciall yet cannot even imagin like real man bed thing great errrectlon provid exactiy want ciali lot advantag viagra effect last hour readi start within minut mix aicohoi ship countri get right',
 'subject la vega high rise boom la vega fast becom major metropolitan citi new high rise tower expect built around la vega strip within next year condominium boom begun buy first earli phase pre construct price avail la vega high rise includ trump cosmopolitan mgm turnberri icon sky among other join interest list http www verticallv com messag sent realti one highris learn www verticallv comif wish exclud futur mail pleas repli word remov subject line',
 'subject save money buy get thing tri ciall yet cannot even imagin like real man bed thing great errrectlon provid exactli want ciaii iot advantaq viagra effect iast hour readi start within minut mix aicohol ship countri get riqht',
 'subject brighten teeth get teeth bright white consid profession teeth whiten know usual cost local dentist visit site learn profession whiten teeth use exact whiten system dentist use fraction cost get show look whiten system show comparison product avail today includ cost know product best market back day money back guarante click learn receiv email internet affili network member would longer like receiv special promot via email internet affili network click unsubscrib',
 'subject wall street phenomenon reap reward small cap stock finder new develop expect move western sierra mine inc stock westernsierramin com western sierra mine compani move fast big news big busi afoot wsrm read find wsrm top pick week western sierra mine profitabi busi mode avoid highest cost associ mine explor essenti wester sierra oper mine site previousiy expior found small argest mine compani yet sti produc handsom profit gioba mine industri boom wi continu foreseeabi futur due impact china driven demand commod price ong suppiy respons lead time news news news read find expect wsrm take week recent news compani phoenix busi wire june oo western sierra mine corp pink sheet wsrm news announc today board director approv author forward split issu outstand common tock al sharehoid record june compani state reason spiit ow addit investor particip long term goal object western phoenix busi wire june western sierra mine pink sheet wsrm news oretech inc pink sheet ort news announc today respect board director agre enter agreement develop silver plume pittsburg mine ocat coiorado comment propos transact presid western sierra mine michael chaffe said new aiignment oretech wil aliow compani util specif expertis maximum benefit oretech tri focu develop proprieti extract technoiogi western expand mine activ u start due dilig properti ook forward take propos back oretech end month phoenix busi wire june western sierra mine pink sheet wsrm news announc today sign letter intent asdi corp provid wsrm right deveiop asdi properti locat crescent vailey battl mountain nev cannot stress enough signific news tock spiit oniy mean one thing good busi spiit date set june obviousiy time get repsect news sma compani would right rich properti speak volum manag near futur earn wouid fortun invoiv industri pioneer oretech noth short extraordinari fortuit event earn wsrm highli recommend symbol wsrm current price short term target price month target price news industri mine tock outperform p dow jone industri averag last three year profit mine compani doubl second year row return equiti increas nearli three fold past two year price waterhous cooper cali anoth bumper year global mine industri oo go say sustain upturn commod price caught investor attent creat dash mine tock add unpreced profit free cash flow buoyant industri inform read mine enter dragon price waterhous cooper locat pwcglobal com disclaim inform within emai contain forward look statement within mean section secur act section b secur exchang act statement express involv discuss respect predict expect belief pian project object goai assumpt futur event perform statement histor fact may forward ook statement forward look statement base expect estim project time statement made involv number risk uncertainti couid caus actual resuit event differ materialiy present anticip forward ook statement action may identifi use word project forese expect wiil anticip estim believ understand statement indic certain action may couid might occur mani micro cap tock today compani addit risk factor worth note factor inciud imit oper histori compani advanc cash relat parti sharehold unsecur basi one vendor reiat parti major tockhoid suppii nineti seven percent compani raw materi reiianc two custom fifti percent busi numer reiat parti transact need rais capit factor other fulli spell compani sec fii urg read file invest rocket stock report repres inform contain messag state ail materia fact omit materia fact necessari make statement therein misiead inform provid within email pertain invest stock secur must understood inform provid invest advic rocket stock report advis reader subscrib seek advic regist profession secur repres decid trade stock featur within email none materi within report shail constru kind invest advic solicit mani compani verg bankruptci ose al mone invest stock publish rocket stock report regist invest advisor subscrib shouid view inform herein egal tax account invest advic refer past perform compani specialiy select referenc base favor perform compani wouid need perfect time achiev resuit exampi given assur happen rememb aiway past perform never indic futur result thorough due dilig effort inciud review compani fii shouid complet prior invest compiianc secur act section b rocket stock report disclos receipt twelv thousand doilar third parti gem inc offic director affiiiat sharehoid circul report gem inc posit stoc k wi seil time without notic awar inher confiict interest resuit compens due fact paid advertis conflict ail factua inform report gather pubiic sourc includ imit compani websit sec fii compani press reieas rocket sto ck report believ inform reiiabl make guarante accuraci compiet use materia within email constitut accept term',
 'subject fpa notic ebay misrepresent ident user suspens section dear ebay member effort protect ebay account secur suspend account time safe restor taken action account may compromis although cannot disclos investig procedur led conclus pleas know took action order maintain safeti account instruct get account reinstat pleas click button bellow thank patienc cooper regard safeharbor departmentebay inc',
 'subject search engin posit first list top search engin immedi compani place busi qualifi websit perman top major search engin guarante never move ex yahoo msn alta vista etc promot includ unlimit traffic go last long interest guarante first posit top search engin promot fee pleas contact us promptli find qualifi via email searchl telefonica net pe import includ url interest promot pay per click exampl provid promot valid usa canada sincer search engin placement specialist wish remov list pleas respond follow email address type word remov subject line search speedi com pe',
 'subject softwar guarante legal name brand softwar low low low low price everyth come hustl wait mani would coward courag enough',
 'subject local softwar languag avail hello would like offer local softwar version qerman french spanish uk mani other iist softwar availabi immedi download need wait week cd deiiveri exampi norton lnternet secur pro window xp profession sp fuil version corei draw graphic suit dreamweav mx homesit includ macromedia studio mx brows site find softwar need nativ ianguaq best reqard lauraie',
 'subject secur alert confirm nation credit union inform',
 'subject st centuri web specialist jrgbm dear profession problem idea need solut sure cost budget accordingli provid detail pleas send free project scope quot includ detail need know variabl consid would glad deliv cut edg solut challeng qualiti equival superior offer domest compani fraction cost domest develop repres number well establish compani staf qualifi softwar develop record success complet hundr small midsiz project ten wide scale project fortun corpor busi analysi consult web design code test port provid full cycl servic work site offshor specialist develop integr internet intranet extranet applic busi applic erp crm system e busi b b b c solut mobil wireless applic desktop applic data warehous secur cryptographi system qualiti base develop partnership lead technolog provid modern project qualiti manag exclus human resourc info click pleas includ phone number happi call cost effect solut experienc team specialist fair rate free quot list technolog platform specialist employ bring best effici cost effect solut applic platform net java ee ibm webspher suit lotu domino bea weblog coldfus oper system window unix ibm databas ms sql oracl db foxpro informix sybas standard activex com asp corba jdbc odbc wap wml info click pleas includ phone number happi call receiv letter mistak pleas click unsubscrib uce transmiss stop cost recipi send repli word remov subject line ref u senat bill titl section',
 'subject med girl happi girl unsatisfi potenc wait find anoth men click choos great varieti llcens love bs best pri es fast shippinq guarante effect buy riqht warehous store verifi bbb approv visa',
 'subject wearabl electron hi name jason recent visit www clothingplu fi want offer servic could help wearabl electron websit creat websit mean busi best part recreat site initi setup give user friendli master control panel abil easili add remov copi text pictur product price etc want would happi contact brainstorm idea regard jasononlin store creatorstol free ext http www com',
 'subject top level logo busi ident corpor imag say lot thing compani contemporari rhythm life dynam sometim take oniy sever second compani rememb lost among competitor get logo busi stationeri websit done riqht fast turnaround wiil see severai ioqo variant three busi day satisfact quarante provid unlimit amount chang sure wiil meet need fit busi fiexibl discount iogo improv addit format bulk order special packag creativ design competit price look right',
 'subject trust sourc prescript medic best prescript gener med less anger one sinner soul write like rule life urgent question other gold friend lead foe',
 'subject reli us onlin prescript order home sourc health inform conclus place got tire think man paint brain hand poet thirti year old simpli overgrown child one alway play fairli one win card',
 'subject guzzl like fountain spur rock custom speak girlfriend realli enjoy make homemad erot film get pretend like porn star even though ever two us see one thing realli miss movi money shot frank lucki money shot worth dollar order spur home movi end gigant cum shot would make even veteran porn star jealou thank spur help spice sex life anthoni ky spur realli work improv sperm motil morpholog point girlfriend pregnant fertil blend realli help improv male fertil sperm qualiti adam j san francisco usa http karla choral com spur sheep need disturb go http romano choral com rm php',
 'subject lose answer would amaz connect busi world wide web mani shopper lose figur wouldamaz youlos cannot findyour web site simpl equat notb found lose new custom chang submit websit major search engin around world see full list web site research best effect meta tag keyword use web site rise search enginelist new custom find lose custom let us profession manag submiss web site get itfound seen world search engin click onthi link click discov thepow connect busi world wide web',

Creating the bag of words model

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1600)
X=cv.fit_transform(bag).toarray()
y=data['spam']

Splitting the dataset into the training set and test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25, random_state=0)

# Training the Naive Bayes model on the training set

In [14]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

Predicting the Test set results

In [15]:
y_pred=classifier.predict(X_test)

Making the confusion matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1039   50]
 [  23  320]]

0.9490223463687151

To check model prediction

In [30]:
new_review="dr . kaminski called me back telling me that he would like to have you as  an intern student in his research department during the summer . please  write him an email as soon as possible to introduce yourself and letting  him know of your expected starting date and ending date"
new_review=re.sub('[^a-zA-Z]',' ',new_review)
new_review=new_review.lower()
new_review=new_review.split()
ps=PorterStemmer()
all_stopwords=stopwords.words('english')
all_stopwords.remove('not')
new_review=[ps.stem(word) for word in new_review if not word in set(all_stopwords)]
new_review=" ".join(new_review)
new_corpus=[new_review]
new_X_test=cv.transform(new_corpus).toarray()
new_y_pred=classifier.predict(new_X_test)
print(new_y_pred)

[0]

# Training the Random Forest model on the training set

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [32]:
cls=RandomForestClassifier()
n_estimators=[25,50,75,100,125,150,175,200]
default=100
criterion=['gini','entropy']
max_depth=[3,5,10]
parameters={'n_estimators':n_estimators,'criterion':criterion,'max_depth':max_depth}
rfc=GridSearchCV(cls,parameters)
rfc.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 10],
                         'n_estimators': [25, 50, 75, 100, 125, 150, 175, 200]})

In [33]:
rf_pred=rfc.predict(X_test)

In [34]:
confusion_matrix(y_test,rf_pred)

array([[1087,    2],
       [  82,  261]])

In [35]:
accuracy_score(y_test,rf_pred)

0.9413407821229051